/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Email + password only. Reader/Writer capabilities are inferred from activity, never chosen at signup.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description User registered. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisteredUser"];
                    };
                };
                /** @description Email and password are required. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and get tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Access + refresh token pair. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Email and password are required. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid credentials or deactivated account. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Rotates the refresh token on every use.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description New token pair. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description Refresh token is required. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid, expired, or revoked refresh token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile with capabilities. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/writers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searchable list of public writers */
        get: {
            parameters: {
                query?: {
                    /** @description Case-insensitive email filter. */
                    q?: string;
                    /** @description Max writers to return. */
                    limit?: number;
                    /** @description Writers to skip. */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Writer catalog page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WritersList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/writers/{writer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Writer profile and published newsletters
         * @description Posts are paywall-masked for readers without an allocation.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional `Bearer <access_token>`. Full content is returned when the reader has an active allocation to the writer. */
                    Authorization?: string;
                };
                path: {
                    /** @description Writer id. */
                    writer_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Writer with masked posts. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WriterDetail"];
                    };
                };
                /** @description Invalid writer_id format. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Writer not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a subscription
         * @description Starts the monthly subscription via the payment gateway and grants the READER capability.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SubscribeRequest"];
                };
            };
            responses: {
                /** @description Allocation summary. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationSummary"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get allocations and change credits */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Allocation summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationSummary"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/allocations/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign a writer to an empty slot
         * @description Filling an empty slot consumes 0 change credits.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignRequest"];
                };
            };
            responses: {
                /** @description Updated allocations. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationResult"];
                    };
                };
                /** @description Missing/invalid writer_id or no subscription. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/allocations/swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Swap one writer for another
         * @description Consumes 1 change credit; rejected at 0 remaining credits.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SwapRequest"];
                };
            };
            responses: {
                /** @description Updated allocations. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationResult"];
                    };
                };
                /** @description Missing ids, no subscription, or no credits. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/allocations/{writer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Release a writer slot
         * @description Consumes 1 change credit.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Allocated writer to release. */
                    writer_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated allocations. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationResult"];
                    };
                };
                /** @description Invalid id, no subscription, or no credits. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment gateway webhook
         * @description Public, Stripe-ready. No auth.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookRequest"];
                };
            };
            responses: {
                /** @description Event accepted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResult"];
                    };
                };
                /** @description event_type is required. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a draft or scheduled post
         * @description Any authenticated user may create a first post — doing so grants the WRITER capability.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePostRequest"];
                };
            };
            responses: {
                /** @description Post created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedPost"];
                    };
                };
                /** @description Missing title/preview or bad scheduled_at. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a post immediately */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Draft post id. */
                    post_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published post. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublishedPost"];
                    };
                };
                /** @description Invalid post_id format. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule a draft post */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Draft post id. */
                    post_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        scheduled_at: string;
                    };
                };
            };
            responses: {
                /** @description Scheduled post. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScheduledPost"];
                    };
                };
                /** @description Missing/invalid scheduled_at or post_id. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single post with paywall logic
         * @description Public preview; no auth required.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional `Bearer <access_token>`. Full content is returned when the reader has an active allocation to the writer. */
                    Authorization?: string;
                };
                path: {
                    /** @description Post id. */
                    post_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paywall-applied post. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostView"];
                    };
                };
                /** @description Invalid post_id format. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Post not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Cancel a scheduled post */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Scheduled post id. */
                    post_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled post. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CancelledPost"];
                    };
                };
                /** @description Invalid post_id format. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update post content */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Post id. */
                    post_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdatePostRequest"];
                };
            };
            responses: {
                /** @description Updated post. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdatedPost"];
                    };
                };
                /** @description Invalid post_id format. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/posts/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reader feed from allocated writers
         * @description Empty without an active subscription/allocation (archival included).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Max posts to return. */
                    limit?: number;
                    /** @description Opaque pagination cursor (published_at of the last seen post). */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Feed page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Feed"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/writer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current writer's posts */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by status. */
                    status?: "draft" | "scheduled" | "published" | "cancelled";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Own posts, unmasked. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WriterPosts"];
                    };
                };
                /** @description Missing, invalid, or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks database, Redis, and migrations. 503 when not ready.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Readiness"];
                    };
                };
                /** @description Not ready. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Readiness"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example Unauthorized */
            title: string;
            /** @example 401 */
            status: number;
            detail: string;
            /** @description Alias of detail. */
            message: string;
            /** @example UNAUTHORIZED */
            code: string;
        };
        /** @description No role field: capabilities are inferred from activity. A client-sent `role`, if present, is ignored. */
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RegisteredUser: {
            /** Format: uuid */
            id: string;
            email: string;
            /** Format: date-time */
            created_at: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @description Access TTL in seconds. */
            expires_in: number;
            /** @example Bearer */
            token_type: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        Profile: {
            /** Format: uuid */
            id: string;
            email: string;
            /** Format: date-time */
            created_at: string;
            is_writer: boolean;
            is_reader: boolean;
        };
        /** @description Paywall-applied post. `subscriber_content` is null without an active allocation to the writer (or authorship). */
        PostView: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            writer_id: string;
            title: string;
            preview_content: string;
            /** @example published */
            status: string;
            /** Format: date-time */
            published_at: string | null;
            /** Format: date-time */
            created_at: string;
            subscriber_content: string | null;
            has_full_access: boolean;
        };
        CreatePostRequest: {
            title: string;
            preview_content: string;
            /** @default  */
            subscriber_content: string;
            /**
             * Format: date-time
             * @description ISO 8601. When present the post is created scheduled.
             */
            scheduled_at?: string;
        };
        CreatedPost: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            /** Format: date-time */
            scheduled_for: string | null;
            /** Format: date-time */
            created_at: string;
        };
        PublishedPost: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            /** Format: date-time */
            published_at: string | null;
        };
        ScheduledPost: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            /** Format: date-time */
            scheduled_for: string | null;
        };
        CancelledPost: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
        };
        UpdatedPost: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpdatePostRequest: {
            title?: string;
            preview_content?: string;
            subscriber_content?: string;
        };
        Feed: {
            posts: components["schemas"]["PostView"][];
            next_cursor: string | null;
        };
        /** @description Full post for the owning writer (no paywall masking). */
        WriterPost: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            preview_content: string;
            subscriber_content: string;
            /** Format: date-time */
            scheduled_for: string | null;
            /** Format: date-time */
            published_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        WriterPosts: {
            posts: components["schemas"]["WriterPost"][];
        };
        WriterSummary: {
            /** Format: uuid */
            id: string;
            email: string;
            /** Format: date-time */
            created_at: string;
        };
        WritersList: {
            writers: components["schemas"]["WriterSummary"][];
            total: number;
        };
        WriterDetail: {
            /** Format: uuid */
            id: string;
            email: string;
            /** Format: date-time */
            created_at: string;
            subscriber_post_count: number;
            posts: components["schemas"]["PostView"][];
        };
        AllocationEntry: {
            /**
             * Format: uuid
             * @description Null for an empty slot.
             */
            writer_id: string | null;
            /** Format: date-time */
            allocated_at: string | null;
        };
        /** @description Reader subscription state. When no subscription exists, `subscription_id`/`billing_cycle_start` are null and status is `none`. */
        AllocationSummary: {
            /** Format: uuid */
            subscription_id: string | null;
            /** @example active */
            status: string;
            /** Format: date-time */
            billing_cycle_start: string | null;
            change_credits_remaining: number;
            change_credits_per_cycle: number;
            /** @example 5 */
            total_slots: number;
            allocated_slots: number;
            empty_slots: number;
            allocations: components["schemas"]["AllocationEntry"][];
        };
        AllocationResult: {
            success: boolean;
            credits_spent: number;
            allocations: components["schemas"]["AllocationEntry"][];
        };
        SubscribeRequest: {
            /** @default pm_mock_default */
            payment_method_id: string;
        };
        AssignRequest: {
            /** Format: uuid */
            writer_id: string;
        };
        SwapRequest: {
            /** Format: uuid */
            current_writer_id: string;
            /** Format: uuid */
            new_writer_id: string;
        };
        /** @description Internal `{event_type, payload}` shape or Stripe `{type, data.object}` shape. Unknown subscription ids are accepted without effect. */
        WebhookRequest: Record<string, never>;
        WebhookResult: {
            received: boolean;
        };
        Health: {
            /** @example ok */
            status: string;
        };
        Readiness: {
            /** @example ready */
            status: string;
            /** @description database / redis / migrations, each {ok, detail}. */
            checks: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
